
import type { Metadata } from 'next';
import AppClientLayout from './app-client-layout';
import './globals.css';

export const metadata: Metadata = {
  title: 'Pinclone | Your Visual Discovery Engine',
  description: 'Discover, save, and share inspiring ideas. A clone of Pinterest, generated by Firebase Studio.',
  // themeColor: '#E60023', // Primary color for browser UI theming
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=PT+Sans:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet" />
      </head>
      <body>
        <AppClientLayout>{children}</AppClientLayout>
      </body>
    </html>
  );
}
